school/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "school"

urlpatterns = [
	path("", home, name="home"),
	path("about/", about, name="about"),
	path("subjects/", subjects, name="subjects"),

	path("login/", login_page, name="login_page"),
	path("logout/", logout_user, name="logout_user"),
	path("register/", registration_page, name="registration_page"),

	path("teacher-or-student/", teacher_or_student, name="teacher_or_student"),
	path("subject-detail/<int:id>/", subject_detail, name="subject-detail"),
	path("student-account/", student_account, name="student-account"),

	path("teacher-account/", teacher_account, name="teacher-account"),
	path("delete_file/<int:id>/", delete_file, name="delete_file"),
	path("delete_comment/<int:id>/", delete_comment, name="delete_comment"),

	path("likes/<int:id>/", likes, name="likes"),
	

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('school.urls')),
]

templates/school_template/course-details-prof.html
{% extends 'school_template/base.html' %}
{% load static %}
{% block content %}

    {% include 'school_template/header.html' %}

    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <h2>{{subject.title}}</h2>
                            <p>Početna<span>/</span>{{subject.title}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="container mt-5">
        <h3 class="mb-3">Objavite rad</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Napišite opis/uputstva:</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="uputstva"></textarea>
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
              </div>
              <div class="custom-file">
                <input type="file" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01" name="fajl">
                <label class="custom-file-label" for="inputGroupFile01">Izaberite datoteku</label>
              </div>
            </div>
            <button class="btn btn-success" type="submit">Postavi</button>
    </div>

    <section class="course_details_area section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 course_details_left">
                    <div class="content_wrapper">
                        <h4 class="title">Lekcije</h4>
                        <div class="content">
                            <ul class="course_list">
                                {% for file in files %}
                                <li class="justify-content-between align-items-center d-flex">
                                    <p>{{file.text}}</p>
                                    <a class="btn btn-success" style="float: right;" href="{{file.file.url}}">Otvori</a>
                                    {% if request.user == file.uploader %}
                                    <a class="btn btn-danger" href="{% url 'school:delete_file' file.id %}">Izbriši</a>
                                    {% endif %}
                                </li>
                                <hr>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="form-group mt-5">
                <label for="comment">Dodaj komentar:</label>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input  type="textarea" class="form-control" rows="5" id="comment" name="comment"></input>
                    <button class="btn btn-primary mt-2" type="submit">Objavi</button>
                </form>
            </div>
            {% for comment in comments %}
            {% if comment.for_subject == subject %}
                <div class="alert alert-secondary" role="alert">
                    {{comment.comment}}
                    {% if request.user == comment.author %}
                        <button class="btn-sm btn-danger" style="float: right;"><a href="{% url 'school:delete_comment' comment.id %}">Obriši</a></button>
                    {% endif %}
                     <a href="{% url 'school:likes' comment.id %}"><i class="medium material-icons mr-3" style="float: right; padding: 5px">thumb_up</i></a>
                    <p style="float: right;">{{comment.comment_likes.num_of_likes}}</p>
                    <p>{{comment.author.username}}</p>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </section>
    <!--================ End Course Details Area =================-->

{% endblock %}

templates/school_template/course-details-student.html
{% extends 'school_template/base.html' %}
{% load static %}
{% block content %}

    {% include 'school_template/header.html' %}

    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <h2>{{subject.title}}</h2>
                            <p>Početna<span>/</span>{{subject.title}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!--================ Start Course Details Area =================-->
    <section class="course_details_area section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 course_details_left">
                    <h2>Zadaci za predmet {{subject.title}}:</h2>
                    <div class="content_wrapper">

                        <h4 class="title">Zadaci</h4>
                        <div class="content">
                            <ul class="course_list">
                                {% for file in files %}
                                 <li class="justify-content-between align-items-center d-flex">
                                    <p>{{file.text}}</p>
                                    <a class="btn btn-success" href="{{file.file.url}}">Otvori</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="form-group mt-5">
                <label for="comment">Dodaj komentar:</label>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input  type="textarea" class="form-control" rows="5" id="comment" name="comment"></input>
                    <button class="btn btn-primary mt-2" type="submit">Objavi</button>
                </form>
            </div>
            {% for comment in comments %}
            {% if comment.for_subject.title == subject.title %}
                <div class="alert alert-secondary" role="alert">
                    {{comment.comment}}
                    {% if request.user == comment.author %}
                        <button class="btn-sm btn-danger" style="float: right;"><a href="{% url 'school:delete_comment' comment.id %}">Obriši</a></button>
                    {% endif %}
                    <a href="{% url 'school:likes' comment.id %}"><i class="medium material-icons mr-3" style="float: right; padding: 5px">thumb_up</i></a>
                    <p style="float: right;">{{comment.comment_likes.num_of_likes}}</p>
                    {% if comment.comment_likes.user_who_liked.username == user.username %}
                    <p  style="float: right;">You like this</p>
                    {% endif %}
                    <p>{{comment.author.username}}</p>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </section>
    <!--================ End Course Details Area =================-->

{% endblock %}

templates/school_template/header.html
{% load static %}
    <header class="main_menu single_page_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand logo_1" href="{% url 'school:home' %}"> <img src="{% static 'img/single_page_logo.png'%}" alt="logo"> </a>
                        <a class="navbar-brand logo_2" href="{% url 'school:home' %}"> <img src="{% static 'img/logo.png'%}" alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item justify-content-end"
                            id="navbarSupportedContent">
                            <ul class="navbar-nav align-items-center">
                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'school:home' %}">Početna</a>
                                </li>
                                <li class="nav-item">
                                    {% if not user.is_authenticated %}
                                    <a class="nav-link" href="{% url 'school:login_page' %}">Login</a>
                                    {% else %}
                                    <a class="nav-link" href="{% url 'school:logout_user' %}">Logout</a>
                                    {% endif %}
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'school:subjects' %}">Predmeti</a>
                                </li>
                                {% if not user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'school:registration_page' %}">Napravi nalog</a>
                                </li>
                                {% endif %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Pages
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="single-blog.html">Single blog</a>
                                        <a class="dropdown-item" href="elements.html">Elements</a>
                                    </div>
                                </li>
                                {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="contact.html">Hello, {{user.username}}</a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header part end-->

templates/school_template/index.html
{% extends 'school_template/base.html' %}
{% load static %}
{% block content %}

    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="{% url 'school:home' %}"> <img src="{% static 'img/logo.png' %}" alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item justify-content-end"
                            id="navbarSupportedContent">
                            <ul class="navbar-nav align-items-center">
                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'school:home' %}">Početna</a>
                                </li>
                                <li class="nav-item">
                                    {% if not user.is_authenticated %}
                                    <a class="nav-link" href="{% url 'school:login_page' %}">Login</a>
                                    {% else %}
                                    <a class="nav-link" href="{% url 'school:logout_user' %}">Logout</a>
                                    {% endif %}
                                </li>
                                {% if not user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'school:registration_page' %}">Napravi nalog</a>
                                </li>
                                {% endif %}
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'school:subjects' %}">Predmeti</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Pages
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="single-blog.html">Single blog</a>
                                        <a class="dropdown-item" href="elements.html">Elements</a>
                                    </div>
                                </li>
                                {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="contact.html">Hello, {{user.username}}</a>
                                </li>
                                {% endif %}
                                <li class="d-none d-lg-block">
                                    <a class="btn_1" href="#">Get a Quote</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header part end-->

    <!-- banner part start-->
    <section class="banner_part">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-xl-6">
                    <div class="banner_text">
                        <div class="banner_text_iner">
                            <h5>Zvanična stranica</h5>
                            <h1>JU Gimnazija 'Vaso Pelagić' Brčko</h1>
                            <a href="{% url 'school:subjects' %}" class="btn_1">Pogledaj Predmete</a>
                            <a href="#" class="btn_2">Get Started </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- banner part start-->


    <!-- learning part start-->
    <section class="learning_part">
        <div class="container">
            <div class="row align-items-sm-center align-items-lg-stretch">
                <div class="col-md-7 col-lg-7">
                    <div class="learning_img">
                        <img src="{% static 'img/learning_img.png'%}" alt="">
                    </div>
                </div>
                <div class="col-md-5 col-lg-5">
                    <div class="learning_member_text">
                        <h5>O školi</h5>
                        <h2>Učite bez brige</h2>
                        <p>Fifth saying upon divide divide rule for deep their female all hath brind Days and beast
                            greater grass signs abundantly have greater also
                            days years under brought moveth.</p>
                        <ul>
                            <li><span class="ti-pencil-alt"></span>Him lights given i heaven second yielding seas
                                gathered wear</li>
                            <li><span class="ti-ruler-pencil"></span>Fly female them whales fly them day deep given
                                night.</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- learning part end-->

    <!-- member_counter counter start -->
    <section class="member_counter">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="single_member_counter">
                        <span class="counter">{{all_teachers}}</span>
                        <h4>Svi Učitelji</h4>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_member_counter">
                        <span class="counter">{{all_students}}</span>
                        <h4>Svi učenici</h4>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_member_counter">
                        <span class="counter">{{number_of_active_users}}</span>
                        <h4>Aktivni Učenici</h4>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_member_counter">
                        <span class="counter">{{ofline_students}}</span>
                        <h4>Ofline Učenici</h4>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- member_counter counter end -->


    <!-- learning part start-->
    <section class="advance_feature learning_part">
        <div class="container">
            <div class="row align-items-sm-center align-items-xl-stretch">
                <div class="col-md-6 col-lg-6">
                    <div class="learning_member_text">
                        <h5>Advance feature</h5>
                        <h2>Our Advance Educator
                            Learning System</h2>
                        <p>Fifth saying upon divide divide rule for deep their female all hath brind mid Days
                            and beast greater grass signs abundantly have greater also use over face earth
                            days years under brought moveth she star</p>
                        <div class="row">
                            <div class="col-sm-6 col-md-12 col-lg-6">
                                <div class="learning_member_text_iner">
                                    <span class="ti-pencil-alt"></span>
                                    <h4>Learn Anywhere</h4>
                                    <p>There earth face earth behold she star so made void two given and also our</p>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-12 col-lg-6">
                                <div class="learning_member_text_iner">
                                    <span class="ti-stamp"></span>
                                    <h4>Expert Teacher</h4>
                                    <p>There earth face earth behold she star so made void two given and also our</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="learning_img">
                        <img src="{% static 'img/advance_feature_img.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- learning part end-->

    <!--::blog_part start::-->
    <section class="blog_part section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-5">
                    <div class="section_tittle text-center">
                        <p>Our Blog</p>
                        <h2>Students Blog</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-lg-4 col-xl-4">
                    <div class="single-home-blog">
                        <div class="card">
                            <img src="{% static 'img/blog/blog_1.png' %}" class="card-img-top" alt="blog">
                            <div class="card-body">
                                <a href="#" class="btn_4">Design</a>
                                <a href="blog.html">
                                    <h5 class="card-title">Dry beginning sea over tree</h5>
                                </a>
                                <p>Which whose darkness saying were life unto fish wherein all fish of together called</p>
                                <ul>
                                    <li> <span class="ti-comments"></span>2 Comments</li>
                                    <li> <span class="ti-heart"></span>2k Like</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-4 col-xl-4">
                    <div class="single-home-blog">
                        <div class="card">
                            <img src="{% static 'img/blog/blog_2.png' %}" class="card-img-top" alt="blog">
                            <div class="card-body">
                                <a href="#" class="btn_4">Developing</a>
                                <a href="blog.html">
                                    <h5 class="card-title">All beginning air two likeness</h5>
                                </a>
                                <p>Which whose darkness saying were life unto fish wherein all fish of together called</p>
                                <ul>
                                    <li> <span class="ti-comments"></span>2 Comments</li>
                                    <li> <span class="ti-heart"></span>2k Like</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-4 col-xl-4">
                    <div class="single-home-blog">
                        <div class="card">
                            <img src="{% static 'img/blog/blog_3.png' %}" class="card-img-top" alt="blog">
                            <div class="card-body">
                                <a href="#" class="btn_4">Design</a>
                                <a href="blog.html">
                                    <h5 class="card-title">Form day seasons sea hand</h5>
                                </a>
                                <p>Which whose darkness saying were life unto fish wherein all fish of together called</p>
                                <ul>
                                    <li> <span class="ti-comments"></span>2 Comments</li>
                                    <li> <span class="ti-heart"></span>2k Like</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--::blog_part end::-->

{% endblock %}

templates/school_template/login.html
{% extends 'school_template/base.html' %}
{% block content %}
{% load static %}
<head>
	<title>Login V8</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico'%}"/>

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}">

	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css'%}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css'%}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css'%}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}">
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form p-l-55 p-r-55 p-t-178" method="POST">
					{% csrf_token %}
					<span class="login100-form-title">
						Sign In
					</span>

					<div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Please enter password">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100"></span>
					</div>

					<div class="text-right p-t-13 p-b-23">
						<span class="txt1">
							Zaboravili
						</span>

						<a href="#" class="txt2">
							Korisničko Ime / Lozinku?
						</a>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">
							Sign in
						</button>
					</div>

					<div class="flex-col-c p-t-170 p-b-40">
						<span class="txt1 p-b-9">
							Nemate nalog?
						</span>

						<a href="{% url 'school:registration_page'%}" class="txt3">
							Napravi nalog sad
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	

	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>

	<script src="{% static 'vendor/animsition/js/animsition.min.js'%}"></script>

	<script src="{% static 'vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>

	<script src="{% static 'vendor/select2/select2.min.js'%}"></script>

	<script src="{% static 'vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js'%}"></script>

	<script src="{% static 'vendor/countdowntime/countdowntime.js'%}"></script>

	<script src="{% static 'js/main.js'%}"></script>
	{% endblock %}

</body>

templates/school_template/register.html
{% extends 'school_template/base.html' %}
{% block content %}
{% load static %}

<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form p-l-55 p-r-55 p-t-178" method="POST">
					{% csrf_token %}
					<span class="login100-form-title">
						Sign Up
					</span>

					<div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Please enter email">
						<input class="input100" type="email" name="email" placeholder="Email">
						<span class="focus-input100"></span>
					</div>

					<br>

					<div class="wrap-input100 validate-input" data-validate = "Please enter password">
						<input class="input100" type="password" name="pass1" placeholder="Password">
						<span class="focus-input100"></span>
					</div>

					<br>

					<div class="wrap-input100 validate-input" data-validate = "Please enter password">
						<input class="input100" type="password" name="pass2" placeholder="Confirm Password">
						<span class="focus-input100"></span>
					</div>

					<br>
					<!-- <form method="POST">
						  <h3>Izaberite vrstu naloga:</h3>
						  <input type="radio" id="male" name="gender" value="male">
						  <label for="male">Učenik</label><br>
						  <input type="radio" id="female" name="gender" value="female">
						  <label for="female">Profesor</label><br>
					</form> -->
					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">
							Sign in
						</button>
					</div>

					<div class="flex-col-c p-t-170 p-b-40">
						<span class="txt1 p-b-9">
							Already have an account?
						</span>

						<a href="{% url 'school:login_page'%}" class="txt3">
							Log in now
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	

	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>

	<script src="{% static 'vendor/animsition/js/animsition.min.js'%}"></script>

	<script src="{% static 'vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>

	<script src="{% static 'vendor/select2/select2.min.js'%}"></script>

	<script src="{% static 'vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js'%}"></script>

	<script src="{% static 'vendor/countdowntime/countdowntime.js'%}"></script>

	<script src="{% static 'js/main.js'%}"></script>
	

</body>

{% endblock %}

templates/school_template/teacher_or_student.html
{% extends 'school_template/base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
	<center>
		<div class="limiter">
				<div class="wrap-login100">
				<center>
					<h1>Kakav nalog pravite?</h1>
					<a href="{% url 'school:teacher-account' %}"><h1>Profesor</h1></a>
					<a href="{% url 'school:student-account' %}"><h1>Učenik</h1></a>
				</center>
				</div>
		</div>
	</center>
<br>
<br>
<br>
{% endblock %}